#!/bin/bash

# 
# 文件占用空间

lsof -n | grep deleted | grep java| awk -F " " '{print $9}'| grep kingdee|awk -F"/" '{print $4}'|uniq -c|wc -l

lsof -n | grep deleted | grep java| awk -F " " '{print $7,$9}'| sort -rnk 1

lsof -n | grep deleted | grep java| awk -F " " '{print $9}'| grep kingdee|awk -F"/" '{print $4}'|uniq -c > servicename.txt

for name in `cat servicename.txt`
do

	if [ $? -eq 0 ]
	then
		echo " $name restart ok "
	else
		echo " $name  error "
	fi
	sleep 1

done

