FROM centos

MAINTAINER linl <son.yupeng.lin@gmail.com>

RUN yum -y install ansible

# put my local web site in myApp folder to /var/www
# ADD myApp /var/www
# expose httpd port
# EXPOSE 80
# the command to run
# CMD ["/usr/sbin/apachectl", "-D", "FOREGROUND"]
